version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=captone
      - MONGO_INITDB_ROOT_PASSWORD=capstonePassword
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
